services:
  - docker

before_install:
  - docker build -t $DOCKER_IMAGE:$TRAVIS_COMMIT .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $DOCKER_IMAGE:$TRAVIS_COMMIT
  - docker run -d $DOCKER_IMAGE:$TRAVIS_COMMIT

script:
  - docker ps | grep -q sloppy

after_success:
  - curl -k -L https://files.sloppy.zone/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - ./sloppy change -v docker_image:"$DOCKER_IMAGE:$TRAVIS_COMMIT" -v domain:"$DOMAIN" $SLOPPY_FILE

notifications:
  email:
    recipients:
      - info@sloppy.io
    on_success: never
    on_failure: always
